DEFUALT_ADDRESS = ''
BROADCAST_ADDRESS = '255.255.255.255'
UDP_LISTEN_PORT = 25550

REQUEST_FOR_JOIN = 'REQUEST_4_JOIN'
ACK_FOR_JOIN = 'ACK_4_JOIN'
REQUEST_FOR_NEIGHBOR = 'REQUEST_4_NEIGHBOR'
REQUEST_FOR_FILE = 'REQUEST_4_FILE'

BROADCAST_TIME_LIMIT_IN_SECONDS = 6

DATA_SPLITTER = ';'
