DEFUALT_ADDRESS = ''
BROADCAST_ADDRESS = '255.255.255.255'
BROADCAST_LISTEN_PORT = 25550
UDP_LISTEN_PORT = 25555

REQUEST_FOR_JOIN = 'REQUEST_4_JOIN'
ACK_FOR_JOIN = 'ACK_4_JOIN'
REQUEST_FOR_NEIGHBOR = 'REQUEST_4_NEIGHBOR'
REQUEST_FOR_FILE = 'REQUEST_4_FILE'
FILE_SEARCH_RESULT = 'FILE_SEARCH_RESULT'

BROADCAST_TIME_LIMIT_IN_SECONDS = 2

DATA_SPLITTER = ';'
DATA_LIST_SPLITTER = '#'
DATA_TUPLE_SPLITTER = '@'
CLASS_DATA_SPLITTER = '&'


STATE_SEARCH = "SEARCH"
STATE_WAIT = "WAIT"
STAET_SELECT = "SELECT"
